VERSION: 2
_BASE_: detectron2/configs/COCO-PanopticSegmentation/Base-Panoptic-FPN.yaml

MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  WEIGHTS: "model_final_c10459.pkl"  # Starting weights; adjust as necessary
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
  PANOPTIC_FPN:
    # Adjust the COMBINE parameters based on your dataset's needs
    COMBINE:
      ENABLED: True
      #OVERLAP_THRESHOLD: 0.5
      STUFF_AREA_LIMIT: 4096
      #INSTANCE_CONFIDENCE_THRESH: 0.5
  ROI_HEADS:
    NUM_CLASSES: 11  # 11 "thing" classes (cell)
  SEM_SEG_HEAD:
    NUM_CLASSES: 6   # 6 "stuff" classes (tissue)  (possibly +1)
    LOSS_WEIGHT: 0.5

DATASETS:
  TRAIN: ("PUMA_train",)
  TEST: ("PUMA_test",)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 270000
  STEPS: (210000, 250000)
  WARMUP_ITERS: 1000

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

OUTPUT_DIR: "geojson_to_coco/model_output"
